import type { CryptoPattern } from '../../../types/index.js';

export const cPatterns: CryptoPattern[] = [
  // === OpenSSL ===
  {
    id: 'c-rsa-keygen',
    language: 'c',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/openssl\/rsa\.h/, /openssl\/evp\.h/],
    callPatterns: [
      /RSA_generate_key_ex\s*\(/,
      /RSA_generate_key\s*\(/,
      /EVP_PKEY_keygen\s*\(/,
      /EVP_PKEY_CTX_new_id\s*\(\s*EVP_PKEY_RSA/,
    ],
    description: "RSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'c-rsa-sign',
    language: 'c',
    category: 'digital-signature',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'medium',
    callPatterns: [
      /RSA_sign\s*\(/,
      /RSA_verify\s*\(/,
      /EVP_DigestSignInit\s*\(/,
      /EVP_DigestVerifyInit\s*\(/,
      /EVP_SignFinal\s*\(/,
      /EVP_VerifyFinal\s*\(/,
    ],
    description: "RSA digital signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'c-rsa-encrypt',
    language: 'c',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'medium',
    callPatterns: [
      /RSA_public_encrypt\s*\(/,
      /RSA_private_decrypt\s*\(/,
      /EVP_PKEY_encrypt\s*\(/,
      /EVP_PKEY_decrypt\s*\(/,
    ],
    description: "RSA encryption is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'c-ec-keygen',
    language: 'c',
    category: 'asymmetric-encryption',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/openssl\/ec\.h/, /openssl\/ecdsa\.h/],
    callPatterns: [
      /EC_KEY_generate_key\s*\(/,
      /EC_KEY_new_by_curve_name\s*\(/,
      /ECDSA_sign\s*\(/,
      /ECDSA_do_sign\s*\(/,
      /ECDH_compute_key\s*\(/,
      /EVP_PKEY_CTX_new_id\s*\(\s*EVP_PKEY_EC/,
    ],
    description: "EC key generation and operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for signatures or ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'c-dh-keygen',
    language: 'c',
    category: 'key-exchange',
    algorithm: 'DH',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/openssl\/dh\.h/],
    callPatterns: [
      /DH_generate_key\s*\(/,
      /DH_generate_parameters_ex\s*\(/,
      /DH_compute_key\s*\(/,
      /EVP_PKEY_CTX_new_id\s*\(\s*EVP_PKEY_DH/,
    ],
    description: "Diffie-Hellman key exchange is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'c-dsa-keygen',
    language: 'c',
    category: 'digital-signature',
    algorithm: 'DSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/openssl\/dsa\.h/],
    callPatterns: [
      /DSA_generate_key\s*\(/,
      /DSA_generate_parameters_ex\s*\(/,
      /DSA_sign\s*\(/,
      /EVP_PKEY_CTX_new_id\s*\(\s*EVP_PKEY_DSA/,
    ],
    description: "DSA is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'c-md5',
    language: 'c',
    category: 'weak-hash',
    algorithm: 'MD5',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/openssl\/md5\.h/],
    callPatterns: [
      /MD5_Init\s*\(/,
      /MD5_Update\s*\(/,
      /MD5_Final\s*\(/,
      /MD5\s*\([^)]/,
      /EVP_md5\s*\(\)/,
    ],
    description: 'MD5 is cryptographically broken and unsuitable for any security use',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'c-sha1',
    language: 'c',
    category: 'weak-hash',
    algorithm: 'SHA-1',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/openssl\/sha\.h/],
    callPatterns: [
      /SHA1_Init\s*\(/,
      /SHA1_Update\s*\(/,
      /SHA1_Final\s*\(/,
      /SHA1\s*\([^)]/,
      /EVP_sha1\s*\(\)/,
    ],
    description: 'SHA-1 is cryptographically broken with practical collision attacks',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'c-sha256',
    language: 'c',
    category: 'safe-hash',
    algorithm: 'SHA-256',
    risk: 'safe',
    confidence: 'medium',
    callPatterns: [
      /SHA256_Init\s*\(/,
      /SHA256\s*\([^)]/,
      /SHA384\s*\([^)]/,
      /SHA512\s*\([^)]/,
      /EVP_sha256\s*\(\)/,
      /EVP_sha384\s*\(\)/,
      /EVP_sha512\s*\(\)/,
    ],
    description: 'SHA-256/384/512 are quantum-resistant hash functions',
    migration: 'No migration needed — already quantum-safe',
  },
  {
    id: 'c-aes',
    language: 'c',
    category: 'safe-symmetric',
    algorithm: 'AES',
    risk: 'safe',
    confidence: 'medium',
    callPatterns: [
      /EVP_aes_\d+_\w+\s*\(\)/,
      /AES_set_encrypt_key\s*\(/,
      /AES_set_decrypt_key\s*\(/,
      /AES_encrypt\s*\(/,
      /AES_cbc_encrypt\s*\(/,
    ],
    description: 'AES is a quantum-resistant symmetric encryption algorithm',
    migration: 'No migration needed — already quantum-safe',
  },
  // === libsodium ===
  {
    id: 'c-libsodium-box',
    language: 'c',
    category: 'key-exchange',
    algorithm: 'Curve25519',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/sodium\.h/],
    callPatterns: [
      /crypto_box_keypair\s*\(/,
      /crypto_box_easy\s*\(/,
      /crypto_box_open_easy\s*\(/,
      /crypto_box_seal\s*\(/,
      /crypto_box_seal_open\s*\(/,
      /crypto_scalarmult\s*\(/,
      /crypto_scalarmult_base\s*\(/,
      /crypto_kx_keypair\s*\(/,
      /crypto_kx_client_session_keys\s*\(/,
      /crypto_kx_server_session_keys\s*\(/,
    ],
    description: "libsodium box/kx uses Curve25519, vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'c-libsodium-sign',
    language: 'c',
    category: 'digital-signature',
    algorithm: 'Ed25519',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/sodium\.h/],
    callPatterns: [
      /crypto_sign_keypair\s*\(/,
      /crypto_sign\s*\(/,
      /crypto_sign_open\s*\(/,
      /crypto_sign_detached\s*\(/,
      /crypto_sign_verify_detached\s*\(/,
      /crypto_sign_ed25519_sk_to_curve25519\s*\(/,
    ],
    description: "libsodium sign uses Ed25519, vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'c-libsodium-aead',
    language: 'c',
    category: 'safe-symmetric',
    algorithm: 'ChaCha20-Poly1305',
    risk: 'safe',
    confidence: 'medium',
    importPatterns: [/sodium\.h/],
    callPatterns: [
      /crypto_aead_chacha20poly1305_ietf_encrypt\s*\(/,
      /crypto_aead_xchacha20poly1305_ietf_encrypt\s*\(/,
      /crypto_aead_chacha20poly1305_ietf_decrypt\s*\(/,
      /crypto_aead_xchacha20poly1305_ietf_decrypt\s*\(/,
      /crypto_secretbox_easy\s*\(/,
      /crypto_secretbox_open_easy\s*\(/,
    ],
    description: 'libsodium AEAD/secretbox uses quantum-resistant symmetric encryption',
    migration: 'No migration needed — already quantum-safe',
  },
  // === wolfSSL ===
  {
    id: 'c-wolfssl-rsa',
    language: 'c',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/wolfssl\/wolfcrypt\/rsa\.h/],
    callPatterns: [
      /wc_RsaKeyGen\s*\(/,
      /wc_MakeRsaKey\s*\(/,
      /wc_RsaPublicEncrypt\s*\(/,
      /wc_RsaPrivateDecrypt\s*\(/,
      /wc_RsaSSL_Sign\s*\(/,
      /wc_RsaSSL_Verify\s*\(/,
    ],
    description: "wolfSSL RSA operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  // === mbedTLS ===
  {
    id: 'c-mbedtls-rsa',
    language: 'c',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/mbedtls\/rsa\.h/],
    callPatterns: [
      /mbedtls_rsa_gen_key\s*\(/,
      /mbedtls_rsa_pkcs1_encrypt\s*\(/,
      /mbedtls_rsa_pkcs1_decrypt\s*\(/,
      /mbedtls_rsa_pkcs1_sign\s*\(/,
      /mbedtls_rsa_pkcs1_verify\s*\(/,
    ],
    description: "mbedTLS RSA operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'c-mbedtls-ec',
    language: 'c',
    category: 'digital-signature',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/mbedtls\/ecdsa\.h/, /mbedtls\/ecp\.h/],
    callPatterns: [
      /mbedtls_ecdsa_genkey\s*\(/,
      /mbedtls_ecdsa_write_signature\s*\(/,
      /mbedtls_ecdsa_read_signature\s*\(/,
      /mbedtls_ecdh_gen_public\s*\(/,
      /mbedtls_ecdh_compute_shared\s*\(/,
    ],
    description: "mbedTLS EC operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for signatures or ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  // === PQC (liboqs) ===
  {
    id: 'c-pqc-oqs-kem',
    language: 'c',
    category: 'pqc-algorithm',
    algorithm: 'ML-KEM',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [/#include\s+[<"]oqs\/oqs\.h[>"]/],
    callPatterns: [
      /OQS_KEM_new\s*\(/,
      /OQS_KEM_keypair\s*\(/,
      /OQS_KEM_encaps\s*\(/,
      /OQS_KEM_decaps\s*\(/,
    ],
    description: 'liboqs ML-KEM (FIPS 203) key encapsulation',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
  },
  {
    id: 'c-pqc-oqs-sig',
    language: 'c',
    category: 'pqc-algorithm',
    algorithm: 'ML-DSA',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [/#include\s+[<"]oqs\/oqs\.h[>"]/],
    callPatterns: [
      /OQS_SIG_new\s*\(/,
      /OQS_SIG_sign\s*\(/,
      /OQS_SIG_verify\s*\(/,
    ],
    description: 'liboqs ML-DSA (FIPS 204) digital signature',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
  },
];
