import type { CryptoPattern } from '../../../types/index.js';

export const goPatterns: CryptoPattern[] = [
  {
    id: 'go-rsa-keygen',
    language: 'go',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/"crypto\/rsa"/],
    callPatterns: [/rsa\.GenerateKey\s*\(/],
    keySizeExtractor: /GenerateKey\s*\([^,]*,\s*(\d+)\s*\)/,
    description: "RSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'go-rsa-sign',
    language: 'go',
    category: 'digital-signature',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /rsa\.SignPKCS1v15\s*\(/,
      /rsa\.SignPSS\s*\(/,
    ],
    description: "RSA digital signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'go-rsa-encrypt',
    language: 'go',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /rsa\.EncryptOAEP\s*\(/,
      /rsa\.EncryptPKCS1v15\s*\(/,
      /rsa\.DecryptOAEP\s*\(/,
      /rsa\.DecryptPKCS1v15\s*\(/,
    ],
    description: "RSA encryption is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'go-ecdsa-keygen',
    language: 'go',
    category: 'asymmetric-encryption',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/"crypto\/ecdsa"/],
    callPatterns: [/ecdsa\.GenerateKey\s*\(/],
    contextPatterns: [/elliptic\.P(?:224|256|384|521)\s*\(\)/],
    description: "ECDSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'go-ecdsa-sign',
    language: 'go',
    category: 'digital-signature',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /ecdsa\.Sign\s*\(/,
      /ecdsa\.SignASN1\s*\(/,
      /ecdsa\.Verify\s*\(/,
      /ecdsa\.VerifyASN1\s*\(/,
    ],
    description: "ECDSA signing/verification is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'go-ed25519',
    language: 'go',
    category: 'digital-signature',
    algorithm: 'Ed25519',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /"crypto\/ed25519"/,
      /"golang\.org\/x\/crypto\/ed25519"/,
    ],
    callPatterns: [
      /ed25519\.GenerateKey\s*\(/,
      /ed25519\.Sign\s*\(/,
    ],
    description: "Ed25519 signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'go-dsa-keygen',
    language: 'go',
    category: 'digital-signature',
    algorithm: 'DSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/"crypto\/dsa"/],
    callPatterns: [
      /dsa\.GenerateKey\s*\(/,
      /dsa\.GenerateParameters\s*\(/,
    ],
    description: "DSA is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'go-curve25519',
    language: 'go',
    category: 'key-exchange',
    algorithm: 'X25519',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/"golang\.org\/x\/crypto\/curve25519"/],
    callPatterns: [
      /curve25519\.X25519\s*\(/,
      /curve25519\.ScalarMult\s*\(/,
    ],
    description: "Curve25519 key exchange is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'go-nacl-box',
    language: 'go',
    category: 'key-exchange',
    algorithm: 'NaCl-Box',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /"golang\.org\/x\/crypto\/nacl\/box"/,
      /"golang\.org\/x\/crypto\/nacl\/sign"/,
    ],
    callPatterns: [
      /box\.GenerateKey\s*\(/,
      /box\.Seal\s*\(/,
      /box\.Open\s*\(/,
      /sign\.GenerateKey\s*\(/,
    ],
    description: "NaCl box/sign uses Curve25519/Ed25519, vulnerable to quantum attacks",
    migration: 'Migrate to ML-KEM (FIPS 203) for key exchange and ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'go-md5',
    language: 'go',
    category: 'weak-hash',
    algorithm: 'MD5',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/"crypto\/md5"/],
    callPatterns: [
      /md5\.New\s*\(/,
      /md5\.Sum\s*\(/,
    ],
    description: 'MD5 is cryptographically broken and unsuitable for any security use',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'go-sha1',
    language: 'go',
    category: 'weak-hash',
    algorithm: 'SHA-1',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/"crypto\/sha1"/],
    callPatterns: [
      /sha1\.New\s*\(/,
      /sha1\.Sum\s*\(/,
    ],
    description: 'SHA-1 is cryptographically broken with practical collision attacks',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'go-sha256',
    language: 'go',
    category: 'safe-hash',
    algorithm: 'SHA-256',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /"crypto\/sha256"/,
      /"crypto\/sha512"/,
    ],
    callPatterns: [
      /sha256\.New\s*\(/,
      /sha256\.Sum256\s*\(/,
      /sha512\.New\s*\(/,
      /sha512\.Sum512\s*\(/,
      /sha512\.New384\s*\(/,
    ],
    description: 'SHA-256/384/512 are quantum-resistant hash functions',
    migration: 'No migration needed — already quantum-safe',
  },
  {
    id: 'go-aes',
    language: 'go',
    category: 'weak-symmetric',
    algorithm: 'AES',
    risk: 'moderate',
    confidence: 'medium',
    importPatterns: [/"crypto\/aes"/],
    callPatterns: [/aes\.NewCipher\s*\(/],
    description: "AES with 128-bit keys provides reduced security against quantum attacks (Grover's algorithm)",
    migration: 'Use AES-256 (32-byte key) for quantum-resistant symmetric encryption',
  },
  {
    id: 'go-pqc-circl-kem',
    language: 'go',
    category: 'pqc-algorithm',
    algorithm: 'ML-KEM',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /circl\/kem\/mlkem/,
      /circl\/kem\/kyber/,
    ],
    callPatterns: [
      /mlkem\.\w+/,
      /kyber\.\w+/,
    ],
    description: 'Cloudflare circl ML-KEM (FIPS 203) implementation',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
  },
  {
    id: 'go-pqc-circl-sig',
    language: 'go',
    category: 'pqc-algorithm',
    algorithm: 'ML-DSA',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /circl\/sign\/mldsa/,
      /circl\/sign\/dilithium/,
    ],
    callPatterns: [
      /mldsa\.\w+/,
      /dilithium\.\w+/,
    ],
    description: 'Cloudflare circl ML-DSA (FIPS 204) implementation',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
  },
  {
    id: 'go-pqc-stdlib',
    language: 'go',
    category: 'pqc-algorithm',
    algorithm: 'ML-KEM',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /crypto\/mlkem/,
      /crypto\/mldsa/,
    ],
    callPatterns: [
      /mlkem\./,
      /mldsa\./,
    ],
    description: 'Go stdlib PQC support (Go 1.24+)',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
  },
];
