import type { CryptoPattern, RiskLevel } from '../../../types/index.js';

export const javaPatterns: CryptoPattern[] = [
  {
    id: 'java-rsa-keygen',
    language: 'java',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/import\s+java\.security\.KeyPairGenerator\s*;/],
    callPatterns: [
      /KeyPairGenerator\.getInstance\s*\(\s*"RSA"\s*\)/,
    ],
    keySizeExtractor: /\.initialize\s*\(\s*(\d+)\s*\)/,
    description: "RSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'java-ec-keygen',
    language: 'java',
    category: 'asymmetric-encryption',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /KeyPairGenerator\.getInstance\s*\(\s*"EC"\s*\)/,
    ],
    contextPatterns: [/ECGenParameterSpec|secp256r1|secp384r1|P-256|P-384/],
    description: "EC key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for signatures or ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'java-dsa-keygen',
    language: 'java',
    category: 'digital-signature',
    algorithm: 'DSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /KeyPairGenerator\.getInstance\s*\(\s*"DSA"\s*\)/,
    ],
    description: "DSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'java-dh-keygen',
    language: 'java',
    category: 'key-exchange',
    algorithm: 'DH',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /KeyPairGenerator\.getInstance\s*\(\s*"DH"\s*\)/,
      /KeyPairGenerator\.getInstance\s*\(\s*"DiffieHellman"\s*\)/,
    ],
    description: "Diffie-Hellman key exchange is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'java-eddsa-keygen',
    language: 'java',
    category: 'digital-signature',
    algorithm: 'EdDSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /KeyPairGenerator\.getInstance\s*\(\s*"EdDSA"\s*\)/,
      /KeyPairGenerator\.getInstance\s*\(\s*"Ed25519"\s*\)/,
      /KeyPairGenerator\.getInstance\s*\(\s*"Ed448"\s*\)/,
    ],
    description: "EdDSA signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'java-rsa-sign',
    language: 'java',
    category: 'digital-signature',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/import\s+java\.security\.Signature\s*;/],
    callPatterns: [
      /Signature\.getInstance\s*\(\s*"SHA\d+withRSA"\s*\)/,
      /Signature\.getInstance\s*\(\s*"RSASSA-PSS"\s*\)/,
    ],
    description: "RSA digital signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'java-ecdsa-sign',
    language: 'java',
    category: 'digital-signature',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /Signature\.getInstance\s*\(\s*"SHA\d+withECDSA"\s*\)/,
    ],
    description: "ECDSA signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'java-key-agreement',
    language: 'java',
    category: 'key-exchange',
    algorithm: 'ECDH/DH',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/import\s+javax\.crypto\.KeyAgreement\s*;/],
    callPatterns: [
      /KeyAgreement\.getInstance\s*\(\s*"ECDH"\s*\)/,
      /KeyAgreement\.getInstance\s*\(\s*"DH"\s*\)/,
      /KeyAgreement\.getInstance\s*\(\s*"DiffieHellman"\s*\)/,
      /KeyAgreement\.getInstance\s*\(\s*"X25519"\s*\)/,
      /KeyAgreement\.getInstance\s*\(\s*"X448"\s*\)/,
      /KeyAgreement\.getInstance\s*\(\s*"XDH"\s*\)/,
    ],
    description: "Key agreement protocols (ECDH/DH/X25519) are vulnerable to quantum attacks",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'java-rsa-cipher',
    language: 'java',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [/import\s+javax\.crypto\.Cipher\s*;/],
    callPatterns: [
      /Cipher\.getInstance\s*\(\s*"RSA\//,
    ],
    description: "RSA encryption is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'java-3des',
    language: 'java',
    category: 'broken-cipher',
    algorithm: '3DES',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /Cipher\.getInstance\s*\(\s*"DESede\//,
      /Cipher\.getInstance\s*\(\s*"DES\//,
    ],
    description: '3DES/DES is deprecated with inadequate security margins',
    migration: 'Migrate to AES-256-GCM for symmetric encryption',
    cweId: 'CWE-327',
  },
  {
    id: 'java-md5',
    language: 'java',
    category: 'weak-hash',
    algorithm: 'MD5',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /import\s+java\.security\.MessageDigest\s*;/,
      /import\s+javax\.crypto\.Mac\s*;/,
    ],
    callPatterns: [
      /MessageDigest\.getInstance\s*\(\s*"MD5"\s*\)/,
      /Mac\.getInstance\s*\(\s*"HmacMD5"\s*\)/,
    ],
    description: 'MD5 is cryptographically broken and unsuitable for any security use',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'java-sha1',
    language: 'java',
    category: 'weak-hash',
    algorithm: 'SHA-1',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /MessageDigest\.getInstance\s*\(\s*"SHA-1"\s*\)/,
      /Mac\.getInstance\s*\(\s*"HmacSHA1"\s*\)/,
    ],
    description: 'SHA-1 is cryptographically broken with practical collision attacks',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'java-sha256',
    language: 'java',
    category: 'safe-hash',
    algorithm: 'SHA-256',
    risk: 'safe',
    confidence: 'high',
    callPatterns: [
      /MessageDigest\.getInstance\s*\(\s*"SHA-256"\s*\)/,
      /MessageDigest\.getInstance\s*\(\s*"SHA-384"\s*\)/,
      /MessageDigest\.getInstance\s*\(\s*"SHA-512"\s*\)/,
      /MessageDigest\.getInstance\s*\(\s*"SHA3-256"\s*\)/,
      /MessageDigest\.getInstance\s*\(\s*"SHA3-384"\s*\)/,
      /MessageDigest\.getInstance\s*\(\s*"SHA3-512"\s*\)/,
      /Mac\.getInstance\s*\(\s*"HmacSHA256"\s*\)/,
      /Mac\.getInstance\s*\(\s*"HmacSHA384"\s*\)/,
      /Mac\.getInstance\s*\(\s*"HmacSHA512"\s*\)/,
    ],
    description: 'SHA-256/384/512/SHA-3 are quantum-resistant hash functions',
    migration: 'No migration needed — already quantum-safe',
  },
  {
    id: 'java-aes-keygen',
    language: 'java',
    category: 'weak-symmetric',
    algorithm: 'AES',
    risk: 'moderate',
    confidence: 'medium',
    importPatterns: [/import\s+javax\.crypto\.KeyGenerator\s*;/],
    callPatterns: [
      /KeyGenerator\.getInstance\s*\(\s*"AES"\s*\)/,
    ],
    keySizeExtractor: /\.init\s*\(\s*(\d+)\s*\)/,
    keySizeRisk: (size: number): RiskLevel => (size >= 256 ? 'safe' : 'moderate'),
    description: "AES-128 provides reduced security against quantum attacks (Grover's algorithm)",
    migration: 'Use AES-256 for quantum-resistant symmetric encryption',
  },
];
