import type { CryptoPattern, RiskLevel } from '../../../types/index.js';

export const javascriptPatterns: CryptoPattern[] = [
  {
    id: 'js-rsa-keygen',
    language: 'javascript',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /import\s+\{[^}]*generateKeyPair(?:Sync)?\s*[^}]*\}\s+from\s+['"](?:node:)?crypto['"]/,
      /(?:const|let|var)\s+\{[^}]*generateKeyPair(?:Sync)?\s*[^}]*\}\s*=\s*require\s*\(\s*['"]crypto['"]\s*\)/,
    ],
    callPatterns: [
      /generateKeyPairSync\s*\(\s*['"]rsa['"]/,
      /generateKeyPairSync\s*\(\s*['"]rsa-pss['"]/,
      /generateKeyPair\s*\(\s*['"]rsa['"]/,
    ],
    keySizeExtractor: /modulusLength\s*:\s*(\d+)/,
    description: "RSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'js-ec-keygen',
    language: 'javascript',
    category: 'asymmetric-encryption',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /generateKeyPairSync\s*\(\s*['"]ec['"]/,
      /generateKeyPair\s*\(\s*['"]ec['"]/,
    ],
    contextPatterns: [/namedCurve\s*:\s*['"](?:P-256|P-384|P-521|secp256k1)['"]/],
    description: "EC key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for signatures or ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'js-ed25519-keygen',
    language: 'javascript',
    category: 'digital-signature',
    algorithm: 'Ed25519',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /generateKeyPairSync\s*\(\s*['"]ed25519['"]\s*\)/,
      /generateKeyPairSync\s*\(\s*['"]ed448['"]\s*\)/,
      /generateKeyPairSync\s*\(\s*['"]x25519['"]\s*\)/,
      /generateKeyPairSync\s*\(\s*['"]x448['"]\s*\)/,
    ],
    description: "Ed25519/X25519 key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for signatures or ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'js-dsa-keygen',
    language: 'javascript',
    category: 'digital-signature',
    algorithm: 'DSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /generateKeyPairSync\s*\(\s*['"]dsa['"]/,
      /generateKeyPair\s*\(\s*['"]dsa['"]/,
    ],
    description: "DSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'js-dh-exchange',
    language: 'javascript',
    category: 'key-exchange',
    algorithm: 'DH',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /import\s+\{[^}]*createDiffieHellman[^}]*\}\s+from\s+['"](?:node:)?crypto['"]/,
      /(?:const|let|var)\s+\{[^}]*createDiffieHellman[^}]*\}\s*=\s*require\s*\(\s*['"]crypto['"]\s*\)/,
    ],
    callPatterns: [/createDiffieHellman\s*\(/],
    description: "Diffie-Hellman key exchange is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'js-ecdh-exchange',
    language: 'javascript',
    category: 'key-exchange',
    algorithm: 'ECDH',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [/createECDH\s*\(/],
    description: "ECDH key exchange is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'js-md5-hash',
    language: 'javascript',
    category: 'weak-hash',
    algorithm: 'MD5',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /createHash\s*\(\s*['"]md5['"]\s*\)/,
      /crypto\.subtle\.digest\s*\(\s*['"]MD5['"]/,
    ],
    description: 'MD5 is cryptographically broken and unsuitable for any security use',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'js-sha1-hash',
    language: 'javascript',
    category: 'weak-hash',
    algorithm: 'SHA-1',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /createHash\s*\(\s*['"]sha1['"]\s*\)/,
      /crypto\.subtle\.digest\s*\(\s*['"]SHA-1['"]/,
    ],
    description: 'SHA-1 is cryptographically broken with practical collision attacks',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'js-sha256-hash',
    language: 'javascript',
    category: 'safe-hash',
    algorithm: 'SHA-256',
    risk: 'safe',
    confidence: 'high',
    callPatterns: [
      /createHash\s*\(\s*['"]sha256['"]\s*\)/,
      /createHash\s*\(\s*['"]sha384['"]\s*\)/,
      /createHash\s*\(\s*['"]sha512['"]\s*\)/,
      /crypto\.subtle\.digest\s*\(\s*['"]SHA-256['"]/,
      /crypto\.subtle\.digest\s*\(\s*['"]SHA-384['"]/,
      /crypto\.subtle\.digest\s*\(\s*['"]SHA-512['"]/,
    ],
    description: 'SHA-256/384/512 are quantum-resistant hash functions',
    migration: 'No migration needed — already quantum-safe',
  },
  {
    id: 'js-aes',
    language: 'javascript',
    category: 'weak-symmetric',
    algorithm: 'AES',
    risk: 'moderate',
    confidence: 'medium',
    callPatterns: [
      /createCipheriv\s*\(\s*['"]aes-\d+-/,
      /createDecipheriv\s*\(\s*['"]aes-\d+-/,
    ],
    keySizeExtractor: /aes-(\d+)/,
    keySizeRisk: (size: number): RiskLevel => (size >= 256 ? 'safe' : 'moderate'),
    description: "AES-128 provides reduced security against quantum attacks (Grover's algorithm)",
    migration: 'Use AES-256 for quantum-resistant symmetric encryption',
  },
  {
    id: 'js-3des',
    language: 'javascript',
    category: 'broken-cipher',
    algorithm: '3DES',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /createCipheriv\s*\(\s*['"]des-ede3-/,
      /createDecipheriv\s*\(\s*['"]des-ede3-/,
    ],
    description: '3DES is deprecated with inadequate security margins',
    migration: 'Migrate to AES-256-GCM for symmetric encryption',
    cweId: 'CWE-327',
  },
  {
    id: 'js-webcrypto-rsa',
    language: 'javascript',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /subtle\.generateKey\s*\(\s*\{[^}]*name\s*:\s*['"]RSA-OAEP['"]/,
      /subtle\.generateKey\s*\(\s*\{[^}]*name\s*:\s*['"]RSA-PSS['"]/,
      /subtle\.generateKey\s*\(\s*\{[^}]*name\s*:\s*['"]RSASSA-PKCS1-v1_5['"]/,
      /subtle\.importKey\s*\([^)]*['"]RSA-OAEP['"]/,
    ],
    description: "WebCrypto RSA operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) or ML-DSA (FIPS 204) when WebCrypto supports PQC',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'js-webcrypto-ec',
    language: 'javascript',
    category: 'asymmetric-encryption',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /subtle\.generateKey\s*\(\s*\{[^}]*name\s*:\s*['"]ECDSA['"]/,
      /subtle\.generateKey\s*\(\s*\{[^}]*name\s*:\s*['"]ECDH['"]/,
      /subtle\.sign\s*\(\s*\{[^}]*name\s*:\s*['"]ECDSA['"]/,
    ],
    description: "WebCrypto EC operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for signatures or ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'js-jwt-sign',
    language: 'javascript',
    category: 'digital-signature',
    algorithm: 'RSA/ECDSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /import\s+.*from\s+['"]jsonwebtoken['"]/,
      /import\s+\{[^}]*SignJWT[^}]*\}\s+from\s+['"]jose['"]/,
      /require\s*\(\s*['"]jsonwebtoken['"]\s*\)/,
    ],
    callPatterns: [
      /jwt\.sign\s*\([^)]*algorithm\s*:\s*['"](?:RS|ES|PS)\d{3}['"]/,
      /jwt\.sign\s*\([^)]*algorithm\s*:\s*['"]EdDSA['"]/,
      /SignJWT\s*\([^)]*\).*setProtectedHeader\s*\(\s*\{[^}]*alg\s*:\s*['"](?:RS|ES|PS)\d{3}['"]/,
      /SignJWT\s*\([^)]*\).*setProtectedHeader\s*\(\s*\{[^}]*alg\s*:\s*['"]EdDSA['"]/,
      /generateKeyPair\s*\(\s*['"](?:RS|ES)\d{3}['"]\s*\)/,
    ],
    description: 'JWT signing with RSA/ECDSA/EdDSA uses quantum-vulnerable algorithms',
    migration: 'Use HMAC-based JWT (HS256) for symmetric signing, or await PQC JWT standards',
    cweId: 'CWE-327',
  },
  {
    id: 'js-pqc-liboqs',
    language: 'javascript',
    category: 'pqc-algorithm',
    algorithm: 'ML-KEM',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /require\s*\(\s*['"]liboqs/,
      /from\s+['"]liboqs/,
    ],
    callPatterns: [
      /KeyEncapsulation\s*\(/,
      /Signature\s*\(/,
    ],
    description: 'liboqs-node PQC bindings',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
  },
  {
    id: 'js-pqc-crystals-kyber',
    language: 'javascript',
    category: 'pqc-algorithm',
    algorithm: 'ML-KEM',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /require\s*\(\s*['"]crystals-kyber/,
      /from\s+['"]crystals-kyber/,
      /require\s*\(\s*['"]ml-kem/,
      /from\s+['"]ml-kem/,
    ],
    callPatterns: [
      /MlKem\d*\s*[\.(]/,
      /Kyber\d*\s*[\.(]/,
    ],
    description: 'ML-KEM (Kyber) key encapsulation',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
  },
  {
    id: 'js-pqc-dilithium',
    language: 'javascript',
    category: 'pqc-algorithm',
    algorithm: 'ML-DSA',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /require\s*\(\s*['"]crystals-dilithium/,
      /from\s+['"]crystals-dilithium/,
      /require\s*\(\s*['"]ml-dsa/,
      /from\s+['"]ml-dsa/,
    ],
    callPatterns: [
      /MlDsa\d*\s*[\.(]/,
      /Dilithium\d*\s*[\.(]/,
    ],
    description: 'ML-DSA (Dilithium) digital signature',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
  },
];
