import type { CryptoPattern, RiskLevel } from '../../../types/index.js';

export const pythonPatterns: CryptoPattern[] = [
  {
    id: 'python-rsa-keygen',
    language: 'python',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\s+import\s+rsa/,
      /from\s+Crypto\.PublicKey\s+import\s+RSA/,
    ],
    callPatterns: [
      /rsa\.generate_private_key\s*\(/,
      /RSA\.generate\s*\(/,
    ],
    keySizeExtractor: /key_size\s*=\s*(\d+)|RSA\.generate\s*\(\s*(\d+)/,
    description: "RSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'python-rsa-sign',
    language: 'python',
    category: 'digital-signature',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\s+import\s+padding/,
      /from\s+Crypto\.Signature\s+import/,
    ],
    callPatterns: [
      /\.sign\s*\(.*padding\.(PSS|PKCS1v15)\s*\(/,
      /pkcs1_15\.new\s*\(/,
      /pss\.new\s*\(/,
    ],
    description: "RSA digital signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'python-ec-keygen',
    language: 'python',
    category: 'asymmetric-encryption',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\s+import\s+ec/,
      /from\s+Crypto\.PublicKey\s+import\s+ECC/,
    ],
    callPatterns: [
      /ec\.generate_private_key\s*\(/,
      /ECC\.generate\s*\(/,
    ],
    contextPatterns: [/SECP256R1|SECP384R1|SECP521R1|P-256|P-384|P-521/],
    description: "Elliptic curve key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for signatures or ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'python-ecdsa-sign',
    language: 'python',
    category: 'digital-signature',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [
      /\.sign\s*\(.*ec\.ECDSA\s*\(/,
      /DSS\.new\s*\(/,
    ],
    description: "ECDSA digital signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'python-ecdh-exchange',
    language: 'python',
    category: 'key-exchange',
    algorithm: 'ECDH',
    risk: 'critical',
    confidence: 'high',
    callPatterns: [/\.exchange\s*\(\s*ec\.ECDH\s*\(\)/],
    description: "ECDH key exchange is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'python-x25519',
    language: 'python',
    category: 'key-exchange',
    algorithm: 'X25519',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\.x25519\s+import/,
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\.x448\s+import/,
    ],
    callPatterns: [
      /X25519PrivateKey\.generate\s*\(/,
      /X448PrivateKey\.generate\s*\(/,
    ],
    description: "X25519/X448 key exchange is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'python-ed25519',
    language: 'python',
    category: 'digital-signature',
    algorithm: 'Ed25519',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\.ed25519\s+import/,
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\.ed448\s+import/,
    ],
    callPatterns: [
      /Ed25519PrivateKey\.generate\s*\(/,
      /Ed448PrivateKey\.generate\s*\(/,
    ],
    description: "Ed25519/Ed448 signatures are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'python-dsa-keygen',
    language: 'python',
    category: 'digital-signature',
    algorithm: 'DSA',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\s+import\s+dsa/,
      /from\s+Crypto\.PublicKey\s+import\s+DSA/,
    ],
    callPatterns: [
      /dsa\.generate_private_key\s*\(/,
      /DSA\.generate\s*\(/,
    ],
    description: "DSA key generation is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'python-dh-keygen',
    language: 'python',
    category: 'key-exchange',
    algorithm: 'DH',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /from\s+cryptography\.hazmat\.primitives\.asymmetric\s+import\s+dh/,
    ],
    callPatterns: [/dh\.generate_parameters\s*\(/],
    description: "Diffie-Hellman key exchange is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'python-md5',
    language: 'python',
    category: 'weak-hash',
    algorithm: 'MD5',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /import\s+hashlib/,
      /from\s+Crypto\.Hash\s+import\s+MD5/,
    ],
    callPatterns: [
      /hashlib\.md5\s*\(/,
      /hashlib\.new\s*\(\s*['"]md5['"]/,
      /hashes\.MD5\s*\(/,
      /MD5\.new\s*\(/,
    ],
    description: 'MD5 is cryptographically broken and unsuitable for any security use',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'python-sha1',
    language: 'python',
    category: 'weak-hash',
    algorithm: 'SHA-1',
    risk: 'critical',
    confidence: 'high',
    importPatterns: [
      /import\s+hashlib/,
      /from\s+Crypto\.Hash\s+import\s+SHA1/,
    ],
    callPatterns: [
      /hashlib\.sha1\s*\(/,
      /hashlib\.new\s*\(\s*['"]sha1['"]/,
      /hashes\.SHA1\s*\(/,
      /SHA1\.new\s*\(/,
    ],
    description: 'SHA-1 is cryptographically broken with practical collision attacks',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  {
    id: 'python-sha256',
    language: 'python',
    category: 'safe-hash',
    algorithm: 'SHA-256',
    risk: 'safe',
    confidence: 'high',
    callPatterns: [
      /hashlib\.sha256\s*\(/,
      /hashlib\.sha384\s*\(/,
      /hashlib\.sha512\s*\(/,
      /hashlib\.sha3_256\s*\(/,
      /hashlib\.sha3_384\s*\(/,
      /hashlib\.sha3_512\s*\(/,
      /hashes\.SHA256\s*\(/,
      /hashes\.SHA384\s*\(/,
      /hashes\.SHA512\s*\(/,
      /hashes\.SHA3_256\s*\(/,
    ],
    description: 'SHA-256/384/512/SHA-3 are quantum-resistant hash functions',
    migration: 'No migration needed — already quantum-safe',
  },
  {
    id: 'python-aes',
    language: 'python',
    category: 'weak-symmetric',
    algorithm: 'AES',
    risk: 'moderate',
    confidence: 'medium',
    importPatterns: [
      /from\s+cryptography\.hazmat\.primitives\.ciphers\s+import/,
      /from\s+Crypto\.Cipher\s+import\s+AES/,
    ],
    callPatterns: [
      /algorithms\.AES\s*\(/,
      /AES\.new\s*\(/,
    ],
    keySizeExtractor: /AES(\d+)|key_size\s*=\s*(\d+)/,
    keySizeRisk: (size: number): RiskLevel => (size >= 256 ? 'safe' : 'moderate'),
    description: "AES-128 provides reduced security against quantum attacks (Grover's algorithm)",
    migration: 'Use AES-256 for quantum-resistant symmetric encryption',
  },

  // --- PQC patterns ---
  {
    id: 'python-pqc-oqs-kem',
    language: 'python',
    category: 'pqc-algorithm',
    algorithm: 'ML-KEM',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /import\s+oqs/,
      /from\s+oqs\s+import/,
    ],
    callPatterns: [
      /oqs\.KeyEncapsulation\s*\(/,
      /KeyEncapsulation\s*\(/,
    ],
    description: 'liboqs ML-KEM (FIPS 203) key encapsulation',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
    nistRef: 'FIPS 203',
  },
  {
    id: 'python-pqc-oqs-sig',
    language: 'python',
    category: 'pqc-algorithm',
    algorithm: 'ML-DSA',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /import\s+oqs/,
      /from\s+oqs\s+import/,
    ],
    callPatterns: [
      /oqs\.Signature\s*\(/,
      /Signature\s*\(\s*["'](?:ML-DSA|Dilithium)/,
    ],
    description: 'liboqs ML-DSA (FIPS 204) digital signature',
    migration: 'Already using PQC — verify parameter choices match NIST recommendations',
    nistRef: 'FIPS 204',
  },
  {
    id: 'python-pqc-pqcrypto',
    language: 'python',
    category: 'pqc-algorithm',
    algorithm: 'PQC (pqcrypto)',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [
      /from\s+pqcrypto\.\w+\.\w+\s+import/,
      /import\s+pqcrypto/,
    ],
    callPatterns: [
      /pqcrypto\.\w+\.\w+\./,
      /generate_keypair\s*\(/,
      /encrypt\s*\(/,
      /sign\s*\(/,
    ],
    description: 'pqcrypto Python bindings for PQC algorithms',
    migration: 'Already using PQC — verify algorithm is NIST-approved (ML-KEM, ML-DSA, SLH-DSA)',
  },
];
