import type { CryptoPattern } from '../../../types/index.js';

export const rustPatterns: CryptoPattern[] = [
  // === ring ===
  {
    id: 'rust-ring-agreement',
    language: 'rust',
    category: 'key-exchange',
    algorithm: 'ECDH',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/use ring::agreement/],
    callPatterns: [
      /agreement::EphemeralPrivateKey::generate/,
      /agreement::agree_ephemeral/,
      /agreement::UnparsedPublicKey::new/,
    ],
    description: "ring ECDH key agreement is vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for key encapsulation',
    nistRef: 'FIPS 203',
    cweId: 'CWE-327',
  },
  {
    id: 'rust-ring-signature',
    language: 'rust',
    category: 'digital-signature',
    algorithm: 'Ed25519/RSA/ECDSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/use ring::signature/],
    callPatterns: [
      /signature::Ed25519KeyPair::from_/,
      /signature::RsaKeyPair::from_/,
      /key_pair\.sign\s*\(/,
      /signature::UnparsedPublicKey::new/,
      /signature::EcdsaKeyPair::from_/,
    ],
    description: "ring signature operations (Ed25519/RSA/ECDSA) are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'rust-ring-aead',
    language: 'rust',
    category: 'safe-symmetric',
    algorithm: 'AES-GCM/ChaCha20',
    risk: 'safe',
    confidence: 'medium',
    importPatterns: [/use ring::aead/],
    callPatterns: [
      /aead::SealingKey::new/,
      /aead::OpeningKey::new/,
      /aead::LessSafeKey::new/,
      /aead::UnboundKey::new/,
    ],
    description: 'ring AEAD encryption is quantum-resistant',
    migration: 'No migration needed — already quantum-safe',
  },
  {
    id: 'rust-ring-digest',
    language: 'rust',
    category: 'safe-hash',
    algorithm: 'SHA-256',
    risk: 'safe',
    confidence: 'medium',
    importPatterns: [/use ring::digest/],
    callPatterns: [
      /digest::digest\s*\(/,
      /digest::Context::new/,
    ],
    description: 'ring digest functions are quantum-resistant hash functions',
    migration: 'No migration needed — already quantum-safe',
  },
  // === RustCrypto ===
  {
    id: 'rust-rsa-crate',
    language: 'rust',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/use rsa::/],
    callPatterns: [
      /RsaPrivateKey::new/,
      /RsaPublicKey::new/,
      /RsaPrivateKey::from_/,
      /RsaPublicKey::from_/,
    ],
    description: "RSA operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'rust-ecdsa-crate',
    language: 'rust',
    category: 'digital-signature',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [
      /use ecdsa::/,
      /use p256::ecdsa/,
      /use p384::ecdsa/,
      /use k256::ecdsa/,
    ],
    callPatterns: [
      /SigningKey::random/,
      /SigningKey::from_/,
      /VerifyingKey::from_/,
      /ecdsa::SigningKey/,
    ],
    description: "ECDSA operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for digital signatures',
    nistRef: 'FIPS 204',
    cweId: 'CWE-327',
  },
  {
    id: 'rust-aes-crate',
    language: 'rust',
    category: 'safe-symmetric',
    algorithm: 'AES-GCM/ChaCha20',
    risk: 'safe',
    confidence: 'medium',
    importPatterns: [
      /use aes_gcm::/,
      /use aes::/,
      /use chacha20poly1305::/,
    ],
    callPatterns: [
      /Aes256Gcm::new/,
      /Aes128Gcm::new/,
      /Aes256Gcm::new_from_slice/,
      /Aes128Gcm::new_from_slice/,
      /ChaCha20Poly1305::new/,
      /XChaCha20Poly1305::new/,
    ],
    description: 'AES-GCM and ChaCha20-Poly1305 are quantum-resistant symmetric encryption',
    migration: 'No migration needed — already quantum-safe',
  },
  {
    id: 'rust-sha-crate',
    language: 'rust',
    category: 'safe-hash',
    algorithm: 'SHA-256',
    risk: 'safe',
    confidence: 'medium',
    importPatterns: [/use sha2::/, /use sha3::/],
    callPatterns: [
      /Sha256::digest/,
      /Sha256::new/,
      /Sha384::/,
      /Sha512::/,
    ],
    description: 'SHA-256/384/512 are quantum-resistant hash functions',
    migration: 'No migration needed — already quantum-safe',
  },
  {
    id: 'rust-md5-crate',
    language: 'rust',
    category: 'weak-hash',
    algorithm: 'MD5',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/use md5::/],
    callPatterns: [
      /Md5::digest/,
      /Md5::new/,
    ],
    description: 'MD5 is cryptographically broken and unsuitable for any security use',
    migration: 'Migrate to SHA-256 or SHA-3 for hashing',
    cweId: 'CWE-328',
  },
  // === openssl crate ===
  {
    id: 'rust-openssl-rsa',
    language: 'rust',
    category: 'asymmetric-encryption',
    algorithm: 'RSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/use openssl::rsa/, /use openssl::pkey/],
    callPatterns: [
      /Rsa::generate/,
      /PKey::from_rsa/,
      /Rsa::public_key_from_/,
      /Rsa::private_key_from_/,
    ],
    description: "openssl crate RSA operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-KEM (FIPS 203) for encryption or ML-DSA (FIPS 204) for signatures',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  {
    id: 'rust-openssl-ec',
    language: 'rust',
    category: 'asymmetric-encryption',
    algorithm: 'ECDSA',
    risk: 'critical',
    confidence: 'medium',
    importPatterns: [/use openssl::ec/],
    callPatterns: [
      /EcKey::generate/,
      /EcGroup::from_curve_name/,
      /EcKey::from_/,
    ],
    description: "openssl crate EC operations are vulnerable to quantum attacks via Shor's algorithm",
    migration: 'Migrate to ML-DSA (FIPS 204) for signatures or ML-KEM (FIPS 203) for key exchange',
    nistRef: 'FIPS 203/204',
    cweId: 'CWE-327',
  },
  // === PQC ===
  {
    id: 'rust-pqc-pqcrypto',
    language: 'rust',
    category: 'pqc-algorithm',
    algorithm: 'PQC (pqcrypto)',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [/use\s+pqcrypto::/, /use\s+pqcrypto_\w+/],
    callPatterns: [
      /pqcrypto::\w+::\w+::keypair\s*\(/,
      /pqcrypto::\w+::\w+::encapsulate\s*\(/,
      /pqcrypto::\w+::\w+::sign\s*\(/,
    ],
    description: 'pqcrypto Rust crate for PQC algorithms',
    migration: 'Already using PQC — verify algorithm is NIST-approved (ML-KEM, ML-DSA, SLH-DSA)',
  },
  {
    id: 'rust-pqc-oqs',
    language: 'rust',
    category: 'pqc-algorithm',
    algorithm: 'PQC (oqs)',
    risk: 'safe',
    confidence: 'high',
    importPatterns: [/use\s+oqs::/, /extern\s+crate\s+oqs/],
    callPatterns: [
      /oqs::kem::Kem/,
      /oqs::sig::Sig/,
      /Kem::new\s*\(/,
      /Sig::new\s*\(/,
    ],
    description: 'liboqs Rust bindings for PQC algorithms',
    migration: 'Already using PQC — verify algorithm is NIST-approved (ML-KEM, ML-DSA, SLH-DSA)',
  },
];
